# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticias',
            options={'ordering': ['created_at'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ['created_at'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
