# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160802_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='image',
            field=s3direct.fields.S3DirectField(null=True, verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='noticias',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='Url Seo'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Titulo'),
        ),
    ]
