# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='times',
            options={'ordering': ['first_name'], 'verbose_name': 'Time', 'verbose_name_plural': 'Times'},
        ),
        migrations.RemoveField(
            model_name='partidas',
            name='status',
        ),
    ]
